----
framework: jest
blacklist:
  - "test/algorithms/geometric-test.js##new geometric algorithm##internal new geometric algorithm"
modifiers:
  - type: jest
    cli: "--forbid-pending --no-bail"
postMerge:
  pattern:
    - "test/algorithms/geometric-test.js"
  strategy:
    threshold: <5|100s>
    type: <commit|time>
preMerge:
  pattern:
    - "test/algorithms/geometric-test.js"
    - "test/algorithms/geometric-test.js"
stability:
  consecutive_runs: 10
preRun:
  - npm i
  - npm run react
postRun:
  - node --version
version: 2.0
